### ISSUE TITLE
Compiling and running the example app

### ISSUE THREAD

**Issue by anthonywebb** [particle-iot/ios-app-example-pod#2]
I downloaded the zip from github, opened xcode and hit run, and am hitting a couple errors:

/Users/me/Downloads/spark-setup-ios-example-master/SparkSetupExample-Swift/SparkSetup-Bridging-Header.h:8:10: 'SparkSetup.h' file not found

Can someone confirm how to get a working example going?

**Comment by yeti7** [comment]
I had the same issue. Try changing that to:
#include "Spark-SDK.h"

Also make sure you also downloaded https://github.com/spark/spark-sdk-ios

**Comment by anthonywebb** [comment]
Thanks for the tip @yeti7 I must still have a path wrong or something because files are in red in xcode now and I am still not able to to compile.  Frustrating its not a cleaner example to get running.

**Comment by reallylongaddress** [comment]
Exact same issue, been chasing my tail for > 8 hours.

Disappointing this hasn't been tested and the documentation is negligible at best.

**Comment by reallylongaddress** [comment]
Have to rearrange the header search path, 
![screen shot 2015-09-27 at 4 51 11 pm](https://cloud.githubusercontent.com/assets/84589/10125425/22d3915c-6539-11e5-9c0f-5aef88ddee0b.png)

**Comment by stephenmadsen** [comment]
I still cannot compile the example. I have spark-sdk / spark-setup / spark-example all downloaded. I installed the proper pods and I moved "Headers/Public" to the bottom but it still does not compile. 

Here is my error now :
/Pods/AFNetworking/UIKit+AFNetworking/UIButton+AFNetworking.m:29:9: 'AFImageDownloader.h' file not found

**Comment by yeti7** [comment]
Are you able to compile the old version of the app? You need to open it
through the workspace.

**Comment by stephenmadsen** [comment]
Yep. I can compile old example app. I have it open through the workspace as well.

**Comment by yeti7** [comment]
See if you can reverse-engineer that. We can do a joint session if
you/when want.

**Comment by congngale** [comment]
What wrong guys, the issue has been knowing for a long time?? Any lead to overcome this issue?

**Comment by williamhqs** [comment]
I got this **'SparkSetup.h'** file not found error, it was worked before. But after i made some cleanup for my Xcode and run `pod install` i got this error. 

Comment `pod 'SparkSetup'` run `'`pod install'`` then uncomment it, run `'pod install'` again it works. Seems `'pod update'` works? not quite sure.

If you use "include "SparkSetup.h" " in bridge file as their github set up project mentioned when using swift project, doesn't work at all. You need to use ``import SparkSetup`. 

For '`AFImageDownloader.h`' not found, file the file in afnetworking github project then add them manually.

Really a bad experience use this SDK...

**Comment by AJ9** [comment]
Having the same problem as @williamhqs

**Comment by RaimundasSakalauskas** [comment]
This should be fixed now. Just run 'pod install' after cloning the repo and it should compile. If for some reason this does not work, please reopen the issue.
