### ISSUE TITLE
c.appName

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/ios-app-example-pod#3]
getting the error:
`/spark/ios-sandbox/spark-setup-ios-example/SparkSetupExample-Swift/ViewController.swift:58:9: 'SparkSetupCustomization' does not have a member named 'appName'`

from this code: https://github.com/spark/spark-setup-ios-example/blob/master/SparkSetupExample-Swift/ViewController.swift#L58

**Comment by RaimundasSakalauskas** [comment]
This has been fixed.
