### ISSUE TITLE
Errors building the project on Xcode 7

### ISSUE THREAD

**Issue by Connor-Knabe** [particle-iot/ios-app-example-pod#7]
I cloned the repo and hit go to open a simulator. However I get some errors from AFNetworking(I've attempted to manually add files to no success).  I also don't seem to have the proper keys (keys-dummy.m) Could you explain how this works?)

I've attempted "pod install" in the root directory.

Gives me this despite having cocoapods-keys installed.
[!] Your Podfile requires that the plugin `cocoapods-keys` be installed. Please install it and try installation again.

Any help would be much appreciated, thanks!

**Comment by alanweissman** [comment]
Thanks for posting! I have something very similar in XCode8 Beta.. appreciate any help

no such file or directory: '/Users/aw/dev/spark-setup-ios-example/Pods/CocoaPodsKeys/SparksetupexampleswiftKeys.m'

clang: error: no such file or directory: '/Users/aw/dev/spark-setup-ios-example/Pods/Target Support Files/Keys/Keys-dummy.m'
clang: error: no input files

**Comment by alanweissman** [comment]
sudo chmod -R go+r /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0 will fix the permissions issue after you install cocoapods-keys.. haven't got farther than that yet

**Comment by Connor-Knabe** [comment]
@alanweissman keep me updated would love to hear if you're able to get this working 👍

**Comment by alanweissman** [comment]
@Connor-Knabe I actually found https://github.com/spark/ios-app-example-carthage to be buildable. It took a bit of work, installing Carthage, running Carthage (see https://github.com/spark/ios-app-example-carthage/issues/1), etc.. but I was able to get it working and once it did I was able to connect to my Particle Photon and get it to connect to my WIFI network.

**Comment by Connor-Knabe** [comment]
@alanweissman thank you soo much!! I'll give this a go.

**Comment by scottsuine** [comment]
Trying to compile this in xCode 8 with Legacy Swift enabled and I am stuck on this error

Cannot convert value of type '([AnyObject]?, NSError?) -> Void' to expected argument type '(([SparkDevice]?, NSError?) -> Void)?'

the snippet of code is below

`   dispatch_async(dispatch_get_global_queue(priority, 0)) {
            // logging in
            dispatch_group_wait(loginGroup, DISPATCH_TIME_FOREVER)
            
            // get specific device by name:
            SparkCloud.sharedInstance().getDevices { (sparkDevices:[AnyObject]?, error:NSError?) -> Void in
              
                if let _=error
                {
                    print("Check your internet connectivity")
                }
                else
                {
                    if let devices = sparkDevices as? [SparkDevice]
                    {
                        for device in devices
                        {
                            if device.name == deviceName
                            {
                                print("found a device with name "+deviceName+" in your account")
                                myPhoton = device
                                dispatch_group_leave(deviceGroup)
                            }
                            
                        }
                        if (myPhoton == nil)
                        {
                            print("device with name "+deviceName+" was not found in your account")
                        }
                    }
                }
            }
        }
    }
`

**Comment by idokleinman** [comment]
Change the line to:
`SparkCloud.sharedInstance().getDevices { (sparkDevices:[SparkDevice]?, error:Error?) -> Void in`
as per new Swift syntax and update to latest cloud SDK via `pod update`

**Comment by danlee6992** [comment]
@idokleinman I have tried your fix above, but a still getting the error

` @IBAction func listDevices(_ sender: Any) {
        
        var myPhoton : SparkDevice?
        SparkCloud.sharedInstance().getDevices { (sparkDevices:[SparkDevice]?, error:Error?) -> Void in
            if let _ = error {
                print("Check your internet connectivity")
            }
            else {
                if let d = devices {
                    for device in d {
                        if device.name == "myNewPhotonName" {
                            myPhoton = device
                        }
                    }
                }
            }
        }
            
        }`

**Comment by RaimundasSakalauskas** [comment]
Closing at this seems to be outdated by now. If issue still persists please reopen.
